---
# tasks file for roles/database

- name: Start Front container
  docker_container:
    name: front
    image: guigz534/tp-devops-front:latest
    pull: yes
    networks: 
      - name: network_two
    pull: yes
  