name: CI devops 2025
on:
  # Ce job se déclenche sur push dans main et develop
  push:
    branches:
      - main
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      # Checkout du code source
      - name: Checkout repository
        uses: actions/checkout@v2.5.0

      # Configuration de JDK 21 avec setup-java
      - name: Set up JDK 21
        with:
          java-version: '21'
          distribution: 'corretto'

      # Construction et tests de l'application avec Maven
      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: simple-api
